# Cleveland Museum of Art API 
### Interpretation of the Greek and Roman Art Department Collections

Source: Cleveland Museum of Art API documentation: https://openaccess-api.clevelandart.org/

In [1]:
#importing python packages
import requests
url = "https://openaccess-api.clevelandart.org/api/artworks/?department=Greek%20and%20Roman%20Art" 
response = requests.get(url) 
data = response.json()
import pandas as pd

### Composition of Artworks by 'type' and 'technique'

In [2]:
data.keys()

dict_keys(['info', 'data'])

In [3]:
#Assigning json data to a variable named 'list_of_artworks'. 
list_of_artworks = data['data']

In [4]:
#loading the json data into a dataframe so that I can work with the imported pandas package. 
df = pd.DataFrame(list_of_artworks)

In [5]:
#in the next few steps (till df.columns) I am trying to understand the dataframe(number of rows and columns, first three rows, list of all columns)
df.shape

(687, 58)

In [6]:
df.head(3)

,id,accession_number,share_license_status,tombstone,current_location,title,creation_date,creation_date_earliest,creation_date_latest,artists_tags,...,recently_acquired,record_type,conservation_statement,has_conservation_images,cover_accession_number,is_nazi_era_provenance,impression,alternate_titles,is_highlight,updated_at
0,155665,1991.1,CC0,Red-Figure Calyx-Krater (Mixing Vessel): Medea...,102D Pre-Roman,Red-Figure Calyx-Krater (Mixing Vessel): Medea...,c. 400 BCE,-405,-395,[male],...,False,object,NaN,False,NaN,False,None,[],True,2026-05-29 08:05:15.037000
1,130360,1953.125,CC0,"Torso of a Kouros, c. 550 BCE. Greece, Archaic...",102B Greek,Torso of a Kouros,c. 550 BCE,-555,-545,[],...,False,object,NaN,False,NaN,False,None,[],True,2026-06-26 20:02:45.305000
2,110232,1928.856,CC0,"Sarcophagus, c. 100–125 CE. Italy, Rome, Roman...",103 Roman,Sarcophagus,c. 100–125 CE,100,125,[],...,False,cover,NaN,False,NaN,False,None,[Orestes Sarcophagus],True,2026-05-29 05:52:00.918000

In [7]:
df.columns

Index(['id', 'accession_number', 'share_license_status', 'tombstone',
       'current_location', 'title', 'creation_date', 'creation_date_earliest',
       'creation_date_latest', 'artists_tags', 'culture', 'technique',
       'support_materials', 'department', 'collection', 'type', 'measurements',
       'dimensions', 'state_of_the_work', 'edition_of_the_work', 'copyright',
       'inscriptions', 'exhibitions', 'provenance', 'find_spot',
       'related_works', 'former_accession_numbers', 'did_you_know',
       'description', 'external_resources', 'citations', 'url', 'images',
       'alternate_images', 'creditline', 'image_credit', 'sketchfab_id',
       'sketchfab_url', 'gallery_donor_text', 'athena_id', 'creators',
       'legal_status', 'accession_date', 'sortable_date', 'date_added_to_oa',
       'date_text', 'collapse_artists', 'on_loan', 'recently_acquired',
       'record_type', 'conservation_statement', 'has_conservation_images',
       'cover_accession_number', 'is_nazi_era_provenance', 'impression',
       'alternate_titles', 'is_highlight', 'updated_at'],
      dtype='str')

In [8]:
#Making a list named relevant_columns to extract the columns needed for basic analyses: 
#I am then assigning the extracted columns to a mini data frame named 'artworks.'
#To find the composition of artworks by technique and type. 
relevant_columns = ['id', 'title', 'technique', 'type', 'did_you_know', 'description']
artworks = df[relevant_columns]
artworks.head()

,id,title,technique,type,did_you_know,description
0,155665,Red-Figure Calyx-Krater (Mixing Vessel): Medea...,ceramic,Ceramic,This vase includes scenes connected to two Ath...,The remarkable scene on the front of this vase...
1,130360,Torso of a Kouros,marble,Sculpture,"In antiquity, brightly colored paint would pro...","<br>Known as a <em>kouros</em>, the ancient Gr..."
2,110232,Sarcophagus,Greek marble,Sculpture,"From the Greek word for “flesh-eating,” <em>sa...",The tragic figure Orestes appears three times ...
3,146147,Black-Figure Dinos (Mixing Vessel): Warships (...,ceramic,Ceramic,"Unable to stand on its own, this round-bottome...","Designed for use at a symposium, or drinking p..."
4,105967,Statue of an Athlete,marble,Sculpture,"For many years, this sculpture stood in the ro...",This idealized athlete recalls Greek sculptura...

In [9]:
artworks.shape

(687, 6)

In [10]:
artworks.columns

Index(['id', 'title', 'technique', 'type', 'did_you_know', 'description'], dtype='str')

In [11]:
#Counting artworks by type.
count_of_types = artworks['type'].value_counts()
print("--- Different types of artoworks and the number of pieces for each type ---")
count_of_types

--- Different types of artoworks and the number of pieces for each type ---

type
Sculpture           182
Coins               177
Ceramic             139
Jewelry              68
Metalwork            48
Glass                32
Stone                22
Ivory                 6
Arms and Armor        3
Silver                3
Forgery               2
Cosmetic Objects      1
Mosaic                1
Plaque                1
Painting              1
Vessels               1
Name: count, dtype: int64

In [12]:
#to be epxlored later 
forgery_type = artworks[artworks['type'] == 'Forgery']
forgery_type

,id,title,technique,type,did_you_know,description
543,106267,Portrait Head of a Priest of Isis,limestone,Forgery,NaN,NaN
550,108111,Head of Aphrodite,marble,Forgery,NaN,NaN

In [13]:
#Counting artworks by technique/medium. Note: technique refers to materials of creation. 'Medium' is an alias for technique. 
#In some instances, type and technique could be the same. For e.g. 'Ceramic' denotes 'type' and 'ceramic' denotes 'technique.'
#Source: Cleveland Museum of Art API documentation: https://openaccess-api.clevelandart.org/
count_of_techniques = artworks['technique'].value_counts()
print("----- Counts of medium of artworks ------")
count_of_techniques

----- Counts of medium of artworks ------

technique
silver                   159
ceramic                   95
bronze                    92
marble                    56
terracotta                47
                        ...
shell                      1
burnished earthenware      1
cast bronze                1
green glass                1
flint                      1
Name: count, Length: 97, dtype: int64

In [14]:
#Here, I am finding the top 5 artworks by 'type' and 'technique'. This data lends itself well to a pictogram bar chart. 
#I am also saving the top 5 'types' and 'techniques' as a csv so that I can work on flourish to make a pictogram.  
top_5_types = artworks['type'].value_counts().head(5)
top_5_techniques = artworks['technique'].value_counts().head(5)
top_5_types.to_csv('cleveland_top_types.csv')
top_5_techniques.to_csv('cleveland_top_techniques.csv')

In [15]:
top_5_types

type
Sculpture    182
Coins        177
Ceramic      139
Jewelry       68
Metalwork     48
Name: count, dtype: int64

In [16]:
top_5_techniques

technique
silver        159
ceramic        95
bronze         92
marble         56
terracotta     47
Name: count, dtype: int64

In [17]:
#Here, I want to connect 'type' and 'technique' to answer questions like how many 'Coins' are made out of 'silver?'
# This is for a SANKEY diagram. 
# I am making two lists to hold top 5 values under 'type' column and 'technique' column. 
# Then I am querying my mini dataframe named 'artworks'to find instances that match elements in the 'top_types' and 'top_techniques' lists.
# Then, I am assigning the matched instances to a subset dataframe named 'selected_artworks.' 
# The 'selected_artworks dataframe' (a subset of the 'artworks' dataframe) contains only data related to top 5 types and top 5 techniques.
types_top_5 = ['Sculpture', 'Coins', 'Ceramic', 'Jewelry', 'Metalwork']
techniques_top_5 = ['silver', 'ceramic', 'bronze', 'marble', 'terracotta'] 
selected_artworks = artworks.query("type in @types_top_5 and technique in @techniques_top_5")
print(len(selected_artworks))
type(selected_artworks)

442

pandas.DataFrame

In [18]:
#Here I am cross tabulating the data by counting the 'type' of artwork and then counting the 'technique' to find pair counts.
#https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html
sankey_grid = pd.crosstab(selected_artworks['type'], selected_artworks['technique'])
print (sankey_grid)

technique  bronze  ceramic  marble  silver  terracotta
type
Ceramic         0       95       0       0           5
Coins           3        0       0     147           0
Jewelry        27        0       0       4           0
Metalwork      24        0       0       5           0
Sculpture      38        0      52       0          42

In [19]:
#to be explored later
#terracotta_ceramics = artworks.query("type == 'Ceramic' and technique == 'terracotta'")
#print(terracotta_ceramics)

In [20]:
#Here I am parsing the selected_artworks dataframe (a subset of the 'artworks'dataframe) to count the number of pairs of type and techniqe. 
#For e.g., Coins -silver, Sculpture - marble. I am assigning the count of these pairs (.value_counts) to 'Value'(reset_index). 
# I am adding 'Value' as a column to the dataframe 'sankey_counts' (a subset of the selected_artworks dataframe) as 
#the selected_artworks df does not have 'Values' as a column listing the counts of the type-techniqe pairs
sankey_counts = selected_artworks[['type','technique']].value_counts().reset_index(name = 'Value')
sankey_counts.columns = ['source', 'Target', 'Value'] #flourish accepts these three column headers for sankey charts.
#pair_counts.head(10)
sankey_counts.to_csv("sankey_type_technique.csv", index = False)

### Exhibition History

In [21]:
df.columns

Index(['id', 'accession_number', 'share_license_status', 'tombstone',
       'current_location', 'title', 'creation_date', 'creation_date_earliest',
       'creation_date_latest', 'artists_tags', 'culture', 'technique',
       'support_materials', 'department', 'collection', 'type', 'measurements',
       'dimensions', 'state_of_the_work', 'edition_of_the_work', 'copyright',
       'inscriptions', 'exhibitions', 'provenance', 'find_spot',
       'related_works', 'former_accession_numbers', 'did_you_know',
       'description', 'external_resources', 'citations', 'url', 'images',
       'alternate_images', 'creditline', 'image_credit', 'sketchfab_id',
       'sketchfab_url', 'gallery_donor_text', 'athena_id', 'creators',
       'legal_status', 'accession_date', 'sortable_date', 'date_added_to_oa',
       'date_text', 'collapse_artists', 'on_loan', 'recently_acquired',
       'record_type', 'conservation_statement', 'has_conservation_images',
       'cover_accession_number', 'is_nazi_era_provenance', 'impression',
       'alternate_titles', 'is_highlight', 'updated_at'],
      dtype='str')

In [22]:
#In this analysis, I am trying to find the exhbition history of the artworks in the Greek and Roman Art Department. 
# I am saving a list of columns to a variable named exhibition_data
# I am making a new dataframe named artwork_exhbition from the exhbition_columns list

exhibition_data =  [ 'title', 'type', 'technique', 'creation_date', 'exhibitions', 'url']
exhibited_artworks = df[exhibition_data]
exhibited_artworks.columns

Index(['title', 'type', 'technique', 'creation_date', 'exhibitions', 'url'], dtype='str')

In [23]:
# #Here, I am trying to find out the Greek and Roman artworks that are currently owned by CMA and which 
#were part of the Inaugural Exhibition held in the year 1916. 
# #Source 1: https://archive.org/details/catalogueinaugu00clev/page/n35/mode/2up
# #Source 2: https://library.si.edu/digital-library/book/catalogofinaugur00clev
# #Source 3: https://digitalarchives.clevelandart.org/digital/collection/p17142coll5
inaugural_artworks = exhibited_artworks[
    exhibited_artworks['exhibitions'].astype(str).str.contains("Inaugural Exhibition", na=False, case=False)
]
# inaugural_titles = []
# for work_title in inaugural_artworks['title']:
#     inaugural_titles.append(work_title)
# print(inaugural_titles)

In [24]:
type(inaugural_artworks)
inaugural_artworks.columns

Index(['title', 'type', 'technique', 'creation_date', 'exhibitions', 'url'], dtype='str')

In [25]:
inaugural_artworks.shape

(47, 6)

In [26]:
exhibition_df = inaugural_artworks.drop(columns =['exhibitions'])

In [27]:
exhibition_df.shape

(47, 5)

In [28]:
exhibition_df.to_csv("inaugural_artworks.csv", index = False)